Feed.create!([
  {uid: "astro-ph", source: "arxiv", fullname: "Astrophysics", parent_id: nil, position: 0, subscriptions_count: 0, last_paper_date: nil},
  {uid: "astro-ph.CO", source: "arxiv", fullname: "Cosmology and Extragalactic Astrophysics", parent_id: 1, position: 1, subscriptions_count: 0, last_paper_date: nil},
  {uid: "astro-ph.EP", source: "arxiv", fullname: "Earth and Planetary Astrophysics", parent_id: 1, position: 2, subscriptions_count: 0, last_paper_date: nil},
  {uid: "astro-ph.GA", source: "arxiv", fullname: "Galaxy Astrophysics", parent_id: 1, position: 3, subscriptions_count: 0, last_paper_date: nil},
  {uid: "astro-ph.HE", source: "arxiv", fullname: "High Energy Astrophysical Phenomena", parent_id: 1, position: 4, subscriptions_count: 0, last_paper_date: nil},
  {uid: "astro-ph.IM", source: "arxiv", fullname: "Instrumentation and Methods for Astrophysics", parent_id: 1, position: 5, subscriptions_count: 0, last_paper_date: nil},
  {uid: "astro-ph.SR", source: "arxiv", fullname: "Solar and Stellar Astrophysics", parent_id: 1, position: 6, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat", source: "arxiv", fullname: "Condensed Matter", parent_id: nil, position: 7, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.dis-nn", source: "arxiv", fullname: "Disordered Systems and Neural Networks", parent_id: 8, position: 8, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.mtrl-sci", source: "arxiv", fullname: "Materials Science", parent_id: 8, position: 9, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.mes-hall", source: "arxiv", fullname: "Mesoscale and Nanoscale Physics", parent_id: 8, position: 10, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.other", source: "arxiv", fullname: "Other Condensed Matter", parent_id: 8, position: 11, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.quant-gas", source: "arxiv", fullname: "Quantum Gases", parent_id: 8, position: 12, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.soft", source: "arxiv", fullname: "Soft Condensed Matter", parent_id: 8, position: 13, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.stat-mech", source: "arxiv", fullname: "Statistical Mechanics", parent_id: 8, position: 14, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.str-el", source: "arxiv", fullname: "Strongly Correlated Electrons", parent_id: 8, position: 15, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cond-mat.supr-con", source: "arxiv", fullname: "Superconductivity", parent_id: 8, position: 16, subscriptions_count: 0, last_paper_date: nil},
  {uid: "gr-qc", source: "arxiv", fullname: "General Relativity and Quantum Cosmology", parent_id: nil, position: 17, subscriptions_count: 0, last_paper_date: nil},
  {uid: "hep-ex", source: "arxiv", fullname: "High Energy Physics - Experiment", parent_id: nil, position: 18, subscriptions_count: 0, last_paper_date: nil},
  {uid: "hep-lat", source: "arxiv", fullname: "High Energy Physics - Lattice", parent_id: nil, position: 19, subscriptions_count: 0, last_paper_date: nil},
  {uid: "hep-ph", source: "arxiv", fullname: "High Energy Physics - Phenomenology", parent_id: nil, position: 20, subscriptions_count: 0, last_paper_date: nil},
  {uid: "hep-th", source: "arxiv", fullname: "High Energy Physics - Theory", parent_id: nil, position: 21, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math-ph", source: "arxiv", fullname: "Mathematical Physics", parent_id: nil, position: 22, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nlin", source: "arxiv", fullname: "Nonlinear Sciences", parent_id: nil, position: 23, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nlin.AO", source: "arxiv", fullname: "Adaptation and Self-Organizing Systems", parent_id: 24, position: 24, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nlin.CG", source: "arxiv", fullname: "Cellular Automata and Lattice Gases", parent_id: 24, position: 25, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nlin.CD", source: "arxiv", fullname: "Chaotic Dynamics", parent_id: 24, position: 26, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nlin.SI", source: "arxiv", fullname: "Exactly Solvable and Integrable Systems", parent_id: 24, position: 27, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nlin.PS", source: "arxiv", fullname: "Pattern Formation and Solitons", parent_id: 24, position: 28, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nucl-ex", source: "arxiv", fullname: "Nuclear Experiment", parent_id: nil, position: 29, subscriptions_count: 0, last_paper_date: nil},
  {uid: "nucl-th", source: "arxiv", fullname: "Nuclear Theory", parent_id: nil, position: 30, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics", source: "arxiv", fullname: "Physics", parent_id: nil, position: 31, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.acc-ph", source: "arxiv", fullname: "Accelerator Physics", parent_id: 32, position: 32, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.ao-ph", source: "arxiv", fullname: "Atmospheric and Oceanic Physics", parent_id: 32, position: 33, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.atom-ph", source: "arxiv", fullname: "Atomic Physics", parent_id: 32, position: 34, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.atm-clus", source: "arxiv", fullname: "Atomic and Molecular Clusters", parent_id: 32, position: 35, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.bio-ph", source: "arxiv", fullname: "Biological Physics", parent_id: 32, position: 36, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.chem-ph", source: "arxiv", fullname: "Chemical Physics", parent_id: 32, position: 37, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.class-ph", source: "arxiv", fullname: "Classical Physics", parent_id: 32, position: 38, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.comp-ph", source: "arxiv", fullname: "Computational Physics", parent_id: 32, position: 39, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.data-an", source: "arxiv", fullname: "Data Analysis, Statistics and Probability", parent_id: 32, position: 40, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.flu-dyn", source: "arxiv", fullname: "Fluid Dynamics", parent_id: 32, position: 41, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.gen-ph", source: "arxiv", fullname: "General Physics", parent_id: 32, position: 42, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.geo-ph", source: "arxiv", fullname: "Geophysics", parent_id: 32, position: 43, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.hist-ph", source: "arxiv", fullname: "History and Philosophy of Physics", parent_id: 32, position: 44, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.ins-det", source: "arxiv", fullname: "Instrumentation and Detectors", parent_id: 32, position: 45, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.med-ph", source: "arxiv", fullname: "Medical Physics", parent_id: 32, position: 46, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.optics", source: "arxiv", fullname: "Optics", parent_id: 32, position: 47, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.ed-ph", source: "arxiv", fullname: "Physics Education", parent_id: 32, position: 48, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.soc-ph", source: "arxiv", fullname: "Physics and Society", parent_id: 32, position: 49, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.plasm-ph", source: "arxiv", fullname: "Plasma Physics", parent_id: 32, position: 50, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.pop-ph", source: "arxiv", fullname: "Popular Physics", parent_id: 32, position: 51, subscriptions_count: 0, last_paper_date: nil},
  {uid: "physics.space-ph", source: "arxiv", fullname: "Space Physics", parent_id: 32, position: 52, subscriptions_count: 0, last_paper_date: nil},
  {uid: "quant-ph", source: "arxiv", fullname: "Quantum Physics", parent_id: nil, position: 53, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math", source: "arxiv", fullname: "Mathematics", parent_id: nil, position: 54, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.AG", source: "arxiv", fullname: "Algebraic Geometry", parent_id: 55, position: 55, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.AT", source: "arxiv", fullname: "Algebraic Topology", parent_id: 55, position: 56, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.AP", source: "arxiv", fullname: "Analysis of PDEs", parent_id: 55, position: 57, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.CT", source: "arxiv", fullname: "Category Theory", parent_id: 55, position: 58, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.CA", source: "arxiv", fullname: "Classical Analysis and ODEs", parent_id: 55, position: 59, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.CO", source: "arxiv", fullname: "Combinatorics", parent_id: 55, position: 60, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.AC", source: "arxiv", fullname: "Commutative Algebra", parent_id: 55, position: 61, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.CV", source: "arxiv", fullname: "Complex Variables", parent_id: 55, position: 62, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.DG", source: "arxiv", fullname: "Differential Geometry", parent_id: 55, position: 63, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.DS", source: "arxiv", fullname: "Dynamical Systems", parent_id: 55, position: 64, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.FA", source: "arxiv", fullname: "Functional Analysis", parent_id: 55, position: 65, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.GM", source: "arxiv", fullname: "General Mathematics", parent_id: 55, position: 66, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.GN", source: "arxiv", fullname: "General Topology", parent_id: 55, position: 67, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.GT", source: "arxiv", fullname: "Geometric Topology", parent_id: 55, position: 68, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.GR", source: "arxiv", fullname: "Group Theory", parent_id: 55, position: 69, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.HO", source: "arxiv", fullname: "History and Overview", parent_id: 55, position: 70, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.IT", source: "arxiv", fullname: "Information Theory", parent_id: 55, position: 71, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.KT", source: "arxiv", fullname: "K-Theory and Homology", parent_id: 55, position: 72, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.LO", source: "arxiv", fullname: "Logic", parent_id: 55, position: 73, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.MP", source: "arxiv", fullname: "Mathematical Physics", parent_id: 55, position: 74, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.MG", source: "arxiv", fullname: "Metric Geometry", parent_id: 55, position: 75, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.NT", source: "arxiv", fullname: "Number Theory", parent_id: 55, position: 76, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.NA", source: "arxiv", fullname: "Numerical Analysis", parent_id: 55, position: 77, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.OA", source: "arxiv", fullname: "Operator Algebras", parent_id: 55, position: 78, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.OC", source: "arxiv", fullname: "Optimization and Control", parent_id: 55, position: 79, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.PR", source: "arxiv", fullname: "Probability", parent_id: 55, position: 80, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.QA", source: "arxiv", fullname: "Quantum Algebra", parent_id: 55, position: 81, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.RT", source: "arxiv", fullname: "Representation Theory", parent_id: 55, position: 82, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.RA", source: "arxiv", fullname: "Rings and Algebras", parent_id: 55, position: 83, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.SP", source: "arxiv", fullname: "Spectral Theory", parent_id: 55, position: 84, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.ST", source: "arxiv", fullname: "Statistics Theory", parent_id: 55, position: 85, subscriptions_count: 0, last_paper_date: nil},
  {uid: "math.SG", source: "arxiv", fullname: "Symplectic Geometry", parent_id: 55, position: 86, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs", source: "arxiv", fullname: "Computing Research Repository", parent_id: nil, position: 87, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.AI", source: "arxiv", fullname: "Artificial Intelligence", parent_id: 88, position: 88, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CL", source: "arxiv", fullname: "Computation and Language", parent_id: 88, position: 89, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CC", source: "arxiv", fullname: "Computational Complexity", parent_id: 88, position: 90, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CE", source: "arxiv", fullname: "Computational Engineering, Finance, and Science", parent_id: 88, position: 91, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CG", source: "arxiv", fullname: "Computational Geometry", parent_id: 88, position: 92, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.GT", source: "arxiv", fullname: "Computer Science and Game Theory", parent_id: 88, position: 93, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CV", source: "arxiv", fullname: "Computer Vision and Pattern Recognition", parent_id: 88, position: 94, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CY", source: "arxiv", fullname: "Computers and Society", parent_id: 88, position: 95, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.CR", source: "arxiv", fullname: "Cryptography and Security", parent_id: 88, position: 96, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.DS", source: "arxiv", fullname: "Data Structures and Algorithms", parent_id: 88, position: 97, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.DB", source: "arxiv", fullname: "Databases", parent_id: 88, position: 98, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.DL", source: "arxiv", fullname: "Digital Libraries", parent_id: 88, position: 99, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.DM", source: "arxiv", fullname: "Discrete Mathematics", parent_id: 88, position: 100, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.DC", source: "arxiv", fullname: "Distributed, Parallel, and Cluster Computing", parent_id: 88, position: 101, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.ET", source: "arxiv", fullname: "Emerging Technologies", parent_id: 88, position: 102, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.FL", source: "arxiv", fullname: "Formal Languages and Automata Theory", parent_id: 88, position: 103, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.GL", source: "arxiv", fullname: "General Literature", parent_id: 88, position: 104, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.GR", source: "arxiv", fullname: "Graphics", parent_id: 88, position: 105, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.AR", source: "arxiv", fullname: "Hardware Architecture", parent_id: 88, position: 106, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.HC", source: "arxiv", fullname: "Human-Computer Interaction", parent_id: 88, position: 107, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.IR", source: "arxiv", fullname: "Information Retrieval", parent_id: 88, position: 108, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.IT", source: "arxiv", fullname: "Information Theory", parent_id: 88, position: 109, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.LG", source: "arxiv", fullname: "Learning", parent_id: 88, position: 110, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.LO", source: "arxiv", fullname: "Logic in Computer Science", parent_id: 88, position: 111, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.MS", source: "arxiv", fullname: "Mathematical Software", parent_id: 88, position: 112, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.MA", source: "arxiv", fullname: "Multiagent Systems", parent_id: 88, position: 113, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.MM", source: "arxiv", fullname: "Multimedia", parent_id: 88, position: 114, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.NI", source: "arxiv", fullname: "Networking and Internet Architecture", parent_id: 88, position: 115, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.NE", source: "arxiv", fullname: "Neural and Evolutionary Computing", parent_id: 88, position: 116, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.NA", source: "arxiv", fullname: "Numerical Analysis", parent_id: 88, position: 117, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.OS", source: "arxiv", fullname: "Operating Systems", parent_id: 88, position: 118, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.OH", source: "arxiv", fullname: "Other Computer Science", parent_id: 88, position: 119, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.PF", source: "arxiv", fullname: "Performance", parent_id: 88, position: 120, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.PL", source: "arxiv", fullname: "Programming Languages", parent_id: 88, position: 121, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.RO", source: "arxiv", fullname: "Robotics", parent_id: 88, position: 122, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.SI", source: "arxiv", fullname: "Social and Information Networks", parent_id: 88, position: 123, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.SE", source: "arxiv", fullname: "Software Engineering", parent_id: 88, position: 124, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.SD", source: "arxiv", fullname: "Sound", parent_id: 88, position: 125, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.SC", source: "arxiv", fullname: "Symbolic Computation", parent_id: 88, position: 126, subscriptions_count: 0, last_paper_date: nil},
  {uid: "cs.SY", source: "arxiv", fullname: "Systems and Control", parent_id: 88, position: 127, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio", source: "arxiv", fullname: "Quantitative Biology", parent_id: nil, position: 128, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.BM", source: "arxiv", fullname: "Biomolecules", parent_id: 129, position: 129, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.CB", source: "arxiv", fullname: "Cell Behavior", parent_id: 129, position: 130, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.GN", source: "arxiv", fullname: "Genomics", parent_id: 129, position: 131, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.MN", source: "arxiv", fullname: "Molecular Networks", parent_id: 129, position: 132, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.NC", source: "arxiv", fullname: "Neurons and Cognition", parent_id: 129, position: 133, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.OT", source: "arxiv", fullname: "Other Quantitative Biology", parent_id: 129, position: 134, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.PE", source: "arxiv", fullname: "Populations and Evolution", parent_id: 129, position: 135, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.QM", source: "arxiv", fullname: "Quantitative Methods", parent_id: 129, position: 136, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.SC", source: "arxiv", fullname: "Subcellular Processes", parent_id: 129, position: 137, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-bio.TO", source: "arxiv", fullname: "Tissues and Organs", parent_id: 129, position: 138, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin", source: "arxiv", fullname: "Quantitative Finance", parent_id: nil, position: 139, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.CP", source: "arxiv", fullname: "Computational Finance", parent_id: 140, position: 140, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.GN", source: "arxiv", fullname: "General Finance", parent_id: 140, position: 141, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.PM", source: "arxiv", fullname: "Portfolio Management", parent_id: 140, position: 142, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.PR", source: "arxiv", fullname: "Pricing of Securities", parent_id: 140, position: 143, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.RM", source: "arxiv", fullname: "Risk Management", parent_id: 140, position: 144, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.ST", source: "arxiv", fullname: "Statistical Finance", parent_id: 140, position: 145, subscriptions_count: 0, last_paper_date: nil},
  {uid: "q-fin.TR", source: "arxiv", fullname: "Trading and Market Microstructure", parent_id: 140, position: 146, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat", source: "arxiv", fullname: "Statistics", parent_id: nil, position: 147, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat.AP", source: "arxiv", fullname: "Applications", parent_id: 148, position: 148, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat.CO", source: "arxiv", fullname: "Computation", parent_id: 148, position: 149, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat.ML", source: "arxiv", fullname: "Machine Learning", parent_id: 148, position: 150, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat.ME", source: "arxiv", fullname: "Methodology", parent_id: 148, position: 151, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat.OT", source: "arxiv", fullname: "Other Statistics", parent_id: 148, position: 152, subscriptions_count: 0, last_paper_date: nil},
  {uid: "stat.TH", source: "arxiv", fullname: "Statistics Theory", parent_id: 148, position: 153, subscriptions_count: 0, last_paper_date: nil}
])
